apiVersion: v1
kind: Service
metadata:
  name: jobster-srv
spec:
  type: LoadBalancer
  selector:
    app: jobster
  ports:
    - name : jobster-port
      port: 80
      protocol: TCP
      targetPort: 8000